-- MySQL Script generated by MySQL Workbench
-- Mon Sep  4 23:17:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(45) NOT NULL,
  `MobileNumber` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `PassportData` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brands` (
  `idBrand` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idBrand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Laptops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Laptops` (
  `idLaptop` INT NOT NULL AUTO_INCREMENT,
  `idBrand` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `ScreenSize` VARCHAR(45) NULL,
  `Color` VARCHAR(45) NULL,
  `HardDiskSize` VARCHAR(45) NULL,
  `CPUModel` VARCHAR(45) NULL,
  `RamMemory` VARCHAR(45) NULL,
  `Description` MEDIUMTEXT NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`idLaptop`),
  INDEX `idBrand_idx` (`idBrand` ASC) VISIBLE,
  CONSTRAINT `idBrand`
    FOREIGN KEY (`idBrand`)
    REFERENCES `mydb`.`Brands` (`idBrand`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `idLaptop` INT NOT NULL,
  `OrderNumber` INT NOT NULL,
  `OrdersDate` DATETIME NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `idClient_idx` (`idClient` ASC) VISIBLE,
  INDEX `idLaptop_idx` (`idLaptop` ASC) VISIBLE,
  CONSTRAINT `idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `idLaptop`
    FOREIGN KEY (`idLaptop`)
    REFERENCES `mydb`.`Laptops` (`idLaptop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
